# Site settings
title: The [Code]yssey
header-img: img/home-bg.png
email: phoebelau7@gmail.com
copyright_name: itsphoebee
description: > # this means to ignore newlines until "baseurl:"
  Follow Phoebe's tech adventure! 100% Bad Puns Guaranteed.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  itsphoebee
learn_profile: itsphoebee
email_username: phoebelau7@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
